import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Projects",
    description: "Generated by create next app",
};

export default function ProjectsLayout({children}: {children: React.ReactNode}) {
    return (
        <div className="flex w-[100%] bg-[#F9FAFB] scrollbar">
            <Sidebar />
            <main className="flex flex-col flex-1 p-4 gap-4">
                <Topbar title="Projects" />
                {children}
            </main>
        </div>
    );
}