import ProjectNav from "@/components/ProjectNav";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import ProgressBar from "@/components/ui/ProgressBar";
import { Metadata } from "next";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
    title: "Projects",
    description: "Generated by create next app",
};

export default function ProjectsLayout({children}: {children: React.ReactNode}) {
    return (
        <SidebarProvider className="flex w-full bg-[#F9FAFB] scrollbar">
            <ProgressBar />
            <AppSidebar />
            <SidebarInset>
                <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
                    <div className="flex items-center gap-2 px-4">
                        <SidebarTrigger className="-ml-1" />
                        <Separator
                            orientation="vertical"
                            className="mr-2 data-[orientation=vertical]:h-4"
                        />
                        <Breadcrumb>
                        <BreadcrumbList>
                            <BreadcrumbItem className="hidden md:block">
                            <BreadcrumbLink href="#">
                                Building Your Application
                            </BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator className="hidden md:block" />
                            <BreadcrumbItem>
                            <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                        </Breadcrumb>
                    </div>
                </header>
                <main className="flex flex-col flex-1 p-4 gap-4">
                    <ProjectNav />
                    {children}
                </main>
            </SidebarInset>
        </SidebarProvider>
    );
}