import ProjectNav from "@/components/ProjectNav";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import ProgressBar from "@/components/ui/ProgressBar";
import { Metadata } from "next";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
    title: "Projects",
    description: "Generated by create next app",
};

export default function ProjectsLayout({children}: {children: React.ReactNode}) {
    return (
        <SidebarProvider className="flex w-full bg-[#F9FAFB] scrollbar">
            <ProgressBar />
            <AppSidebar />
            <SidebarInset>
                <Topbar />
                <main className="flex flex-col flex-1 p-4 gap-4">
                    <ProjectNav />
                    {children}
                </main>
            </SidebarInset>
        </SidebarProvider>
    );
}