import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ProjectProvider } from "@/context/ProjectContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
});
export const metadata: Metadata = {
  title: "ProjectTracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProjectProvider>
        <body className={`${poppins.className} antialiased`}>
          {children}
        </body>
      </ProjectProvider>
    </html>
  );
}
